### ISSUE TITLE
Bad argument `raggedright' to `@end' when building on MacOS

### ISSUE THREAD

**Issue by robertlipe** [karlp/openocd-hacks#1]
Symptom:

	fi; \
	rm -rf $backupdir; exit $rc
./doc/openocd.texi:11337: Unknown command `raggedright'.
./doc/openocd.texi:11342: Bad argument `raggedright' to `@end', using `table'.
./doc/openocd.texi:11342: @item found outside of an insertion block.
./doc/openocd.texi:11344: @item found outside of an insertion block.
./doc/openocd.texi:11346: @item found outside of an insertion block.
./doc/openocd.texi:11349: @item found outside of an insertion block.
./doc/openocd.texi:11351: @item found outside of an insertion block.
./doc/openocd.texi:11353: @item found outside of an insertion block.
./doc/openocd.texi:11355: @item found outside of an insertion block.
./doc/openocd.texi:11356: Unknown command `raggedright'.
./doc/openocd.texi:11360: Unmatched `@end'.
./doc/openocd.texi:11360: @item found outside of an insertion block.
./doc/openocd.texi:11363: Unmatched `@end'.
makeinfo: Removing output file `doc/openocd.info' due to errors; use --force to preserve.

Discussion:
https://sourceforge.net/p/openocd/mailman/openocd-devel/thread/CADQtY4AyvmUzR7E0h3jxEmrRPb644-AfgAVjnNe9HuNE-in_+w@mail.gmail.com/

Confirmed cure:
$ brew install texinfo
$ export PATH=/usr/local/opt/texinfo/bin:$PATH

Update your login shell to include this:
$  echo 'export PATH="/opt/homebrew/opt/texinfo/bin:$PATH"' >> ~/.zshrc

This isn't terrible. I  list it here to help the next dev.
Apparently a patch was submitted (somewhere?) in 2015, but this code base doesn't contain that fix.
https://review.openocd.org/c/openocd/+/2781/2/doc/openocd.texi

We could merge that here or just encourage Mac devs to update Texinfo as above. I'm going with the latter for now.

**Comment by karlp** [comment]
this is a regression in the riscv fork of openocd, see [d57ab0b6321a024c3a83e0acb33eeab3b461b607](https://github.com/riscv/riscv-openocd/commit/d57ab0b6321a024c3a83e0acb33eeab3b461b607)  that MRS used as their base.  Another fix is probably one of the tricks to disable building the docs.   ./configure MAKEINFO=true iirc is the easiest way.

**Comment by robertlipe** [comment]
Good tip. Thanx. 

Searches for this failure case turned up inconclusive. Private gerrit instances and xylin bug tracking are apparently not well indexed.

For those dumpster-diving for the specific changes, it looks like the relevant "break" is 
https://review.openocd.org/c/openocd/+/5995/ and "fixed" via a doc change in
https://review.openocd.org/c/openocd/+/6026/3/README.macOS

The TL;DR there is to document in README.macOS exactly what I prescribed above, so there's no real fix needed. I'll consider this fixed. Hopefully this will get picked up by Google (even if closed) and save the next dev some software spelunking.

And, ya, it stinks that the system-provided one is a relic, but so is texinfo in general.
